### ISSUE TITLE
go install fails

### ISSUE THREAD

**Issue by darkn3rd** [hidetatz/kubecolor#101]
Instructions say:

```bash
go install github.com/hidetatz/kubecolor/cmd/kubecolor@latest
```

But this results in: 

```
go install: github.com/hidetatz/kubecolor/cmd/kubecolor@latest: github.com/hidetatz/kubecolor@v0.0.20: parsing go.mod:
	module declares its path as: github.com/dty1er/kubecolor
	        but was required as: github.com/hidetatz/kubecolor
````

**Comment by tillt** [comment]
This works for me: 
```
go install github.com/dty1er/kubecolor/cmd/kubecolor@latest
```

**Comment by evilbulgarian** [comment]
same issue for me as @darkn3rd

**Comment by prune998** [comment]
This is fixed in the new clone of the project.
Get it at https://github.com/kubecolor/kubecolor or `brew install kubecolor/tap/kubecolor` or `go install github.com/kubecolor/kubecolor/cmd/kubecolor@latest`

**Comment by hidetatz** [comment]
This issue is now fixed. Please reopen if it still happens.
