### ISSUE TITLE
After entering kubectl - N and adding tab, the following syntax error will appear

### ISSUE THREAD

**Issue by jjy7pspsjl** [hidetatz/kubecolor#107]
K8s version: v1.23.7
Kubecolor version: 0.0.20

Fault description:
After entering kubectl - N and adding tab, the following syntax error will appear

![image](https://user-images.githubusercontent.com/24741478/184052576-945bb59d-91f4-49fc-b848-938c16ee868c.png)

**Comment by jjy7pspsjl** [comment]
![image](https://user-images.githubusercontent.com/24741478/184052756-77d89956-b67b-46dc-82e5-4ac4c72bedef.png)

No problem with other uses

**Comment by dstuartkelly** [comment]
I believe its related to having kubectl autocomplete enabled and there are a few other reports with the same issue so this is likely a duplicate?
If the following line is in you `~/.bashrc` (or appropriate shell initialization script for your environment `~/.zshrc` `~/.bash_profile` )  commenting it out will stop the autocomplete from working and prevent the error.

```bash
# source <(kubectl completion bash)
```
Take a look at [the README.md section on configuring autocompletion for kubecolor](https://github.com/hidetatz/kubecolor#autocompletion) if this is the issue.

**Comment by prune998** [comment]
This is fixed in the new clone of the project.
Get it at https://github.com/kubecolor/kubecolor or brew install kubecolor/tap/kubecolor

**Comment by jjy7pspsjl** [comment]
First of all, thank you for your reply. I just tested and failed. The same error is reported.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hidetatz/kubecolor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hidetatz/kubecolor] After entering kubectl - N and adding tab, the following syntax error will appear (Issue #107)





 
I believe its related to having kubectl autocomplete enabled and there are a few other reports with the same issue so this is likely a duplicate?
 If the following line is in you ~/.bashrc (or appropriate shell initialization script for your environment ~/.zshrc ~/.bash_profile )  commenting it out will stop the autocomplete from working and prevent the error.
 # source <(kubectl completion bash)
 
Take a look at the README.md section on configuring autocompletion for kubecolor if this is the issue.

**Comment by prune998** [comment]
Can you please give the output of `kubecolor version` ? (that should return the kubectl version)
Try to use `kubectl` version `v1.25.2` or higher... I also had issue with older versions. 

```
kubecolor -n                                                                                                                                                                                                                                   
default                  istio-system              kube-public               opencost               kube-system               ops                       user-history-debugger
```

**Comment by hidetatz** [comment]
I guess this is fixed now. Please reopen if it still persists.
