### ISSUE TITLE
kubecolor breaks on first argument after kubectl

### ISSUE THREAD

**Issue by ciacco206** [hidetatz/kubecolor#108]
Starting with kubectl v1.22, the first argument has changed.

kubectl v1.21.1
![image001](https://user-images.githubusercontent.com/7156577/187470352-26240dfe-db56-4ef4-aab7-c06b85b06065.png)

kubectl v1.22.12
![image002](https://user-images.githubusercontent.com/7156577/187470398-d968f925-c000-4eda-bd70-9bca4c07ab97.png)

This causes issues with tab completion using kubecolor.

kubecolor using kubectl v1.22 on first argument
![image003](https://user-images.githubusercontent.com/7156577/187470797-87257b84-0881-436c-acf3-0bf0b5b51e16.png)

kubecolor using kubectl v1.22 with all other arguments after the first
![image004 60](https://user-images.githubusercontent.com/7156577/187470915-af64f0b1-a06a-4e29-8471-7c7f00e6c73e.png)

**Comment by prune998** [comment]
This is fixed in the new clone of the project.
Get it at https://github.com/kubecolor/kubecolor or brew install kubecolor/tap/kubecolor

**Comment by hidetatz** [comment]
I think this is fixed now
