### ISSUE TITLE
Publish a container image in CI

### ISSUE THREAD

**Issue by anthr76** [hidetatz/kubecolor#73]
Hi there. Thanks for this great project! As a Linux user it's incredibly inconvenient to go grab a new static binary. A lot of k8s centric go apps I wire into shell functions with podman/docker containers. Would it be possible if we can get releases wired up to a image?

**Comment by dty1er** [comment]
@anthr76 
Do you mean you want to run kubecolor by something like `docker run --rm kubecolor:latest get pods` ?

**Comment by anthr76** [comment]
Yup essentially!
