### ISSUE TITLE
REQ: More conditional coloring of `kubectl get pods` column values (like READY column)

### ISSUE THREAD

**Issue by UNOPARATOR** [hidetatz/kubecolor#76]
I like to run a constantly refreshing `kubectl get pods -A` command in a specified interval using `watch` (in mac & linux) or `while (1) {clear; <command_here>; sleep <interval_in_seconds>}` (in windows powershell).

It would be nice conditional coloring for STATUS columns values just like the READY column:
![image](https://user-images.githubusercontent.com/1214176/120491845-3da18780-c3c2-11eb-84b3-6e1b1449c2d6.png)

_For example:_ yellow for "Pending"/"Init:....", red for "Terminating"/"CrashLoopBackOff", green for "Running", grey for "Completed" etc.

**Comment by bcouetil** [comment]
I would insist on adding color convention on top of that (red for KO, green for OK, etc.).

The idea behind this project is good 🤩, but for now it's useless to me (just adding happy colors has no value).

**Comment by hidetatz** [comment]
Let's discuss this in https://github.com/hidetatz/kubecolor/issues/117
