### ISSUE TITLE
 module declares its path as: github.com/dty1er/kubecolor, but was required as: github.com/hidetatz/kubecolor

### ISSUE THREAD

**Issue by vishal-h** [hidetatz/kubecolor#83]

**Comment by vishal-h** [comment]
I guess the title is self explanatory

**Comment by jamesholcomb** [comment]
This seemed to work around it

`go get -u github.com/dty1er/kubecolor/cmd/kubecolor`

**Comment by Hades32** [comment]
Still broken @hidetatz 
```bash
# go install github.com/hidetatz/kubecolor/cmd/kubecolor@v0.0.20
go install: github.com/hidetatz/kubecolor/cmd/kubecolor@v0.0.20: github.com/hidetatz/kubecolor@v0.0.20: parsing go.mod:
        module declares its path as: github.com/dty1er/kubecolor
                but was required as: github.com/hidetatz/kubecolor

# go version
go version go1.17.7 linux/amd64
```

**Comment by diegoumba** [comment]
Hi..

I installed the plugin with the following command with go version 1.17 

go install github.com/dty1er/kubecolor/cmd/kubecolor@latest

Regards

**Comment by integrii** [comment]
this is still an issue... just change the module path to match the repo please!

**Comment by hidetatz** [comment]
This issue is now fixed. Please reopen if it still happens.
