### ISSUE TITLE
Kubecolor breaks krew plugins using fzf (ctx + ns)

### ISSUE THREAD

**Issue by cterence** [hidetatz/kubecolor#85]
Kubecolor breaks some krew plugins using fzf.
For example, `kubecolor ctx` only lists the contexts with coloration instead of enabling the user to choose the context to switch to with fzf.
Here's a screenshot :
![Capture d’écran du 2022-01-06 16-59-18](https://user-images.githubusercontent.com/25285508/148411891-42156ecd-9bba-4d3f-838a-f8ab6375d619.png)
I'm using zsh, version 5.8 on Linux.

**Comment by prune998** [comment]
you can use ` --plain` to revert to default colors for now

**Comment by cterence** [comment]
Okay I didn't try it, it solves my pain point !
I can do `alias kubectl=kubecolor` and `alias kctx=kubecolor --plain ctx` and it works, thanks !

**Comment by prune998** [comment]
@cterence I also added PR to remove the colors on `ctx` and `ns` subcommands... hope it will be merged... 
In the meantime you can close my branch and build `kubecolor` for yourself.
