### ISSUE TITLE
kubecolor autocomplete adds extra symbols

### ISSUE THREAD

**Issue by sitilge** [hidetatz/kubecolor#87]
I've noticed recently that `kubecolor` is adding symbols such as `$'\033'\[33m` when I press tab for autocomplete. I am using the `kubectl` plugin for `oh-my-zsh`. My shell is `zsh`. Pure `/bin/kubectl` autocomplete works fine.

I have another computer with the same setup (using dotfiles) where the same problems occur, having exactly the same `zsh/oh-my-zsh/kubectl/kubecolor` versions.

![image](https://user-images.githubusercontent.com/3306642/149659166-06cfad65-9781-4c0a-8a7e-2c5614d8d3af.png)

**Comment by levmichael3** [comment]
@sitilge it's the same bug as #78

**Comment by hidetatz** [comment]
This is fixed
