### ISSUE TITLE
Brew installation method does not work

### ISSUE THREAD

**Issue by grzesuav** [hidetatz/kubecolor#90]
```shell
==> Tapping hidetatz/tap
Cloning into '/usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 12), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (59/59), 7.89 KiB | 2.63 MiB/s, done.
Resolving deltas: 100% (12/12), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap/Formula/kubecolor.rb
kubecolor: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the hidetatz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap/Formula/kubecolor.rb:9

Error: Cannot tap hidetatz/tap: invalid syntax in tap!
Failed to install [hidetatz/tap/kubecolor]
Some packages were not installed

==> Some tasks were not executed successfully
```

Unsure where the error is, seems in brew formula

**Comment by iamajohn** [comment]
I am also hitting this issue:
`==> Homebrew was updated to version 3.4.0
More detailed release notes are available on the Homebrew Blog:
  https://brew.sh/blog/3.4.0
==> Tapping hidetatz/tap
Cloning into '/usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 12), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (59/59), 7.89 KiB | 2.63 MiB/s, done.
Resolving deltas: 100% (12/12), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap/Formula/kubecolor.rb
kubecolor: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the hidetatz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap/Formula/kubecolor.rb:9

Error: Cannot tap hidetatz/tap: invalid syntax in tap!`

**Comment by martasd** [comment]
I confirm that I am also seeing the same issue with Homebrew version `3.4.0`.

**Comment by ginrod** [comment]
Me too

**Comment by fveas** [comment]
Same problem here... any workaround?

**Comment by kam1kaze** [comment]
@fveas you can install it with the following command:

```
brew install jjuarez/homebrew-tap-1/kubecolor
```

**Comment by martasd** [comment]
> @fveas you can install it with the following command:
> 
> ```
> brew install jjuarez/homebrew-tap-1/kubecolor
> ```

Works for me. 👍

**Comment by ayaz** [comment]
> @fveas you can install it with the following command:
> 
> ```
> brew install jjuarez/homebrew-tap-1/kubecolor
> ```

Thank you. That worked.

**Comment by BK-STAR77** [comment]
same issue the official tap repo didn't work

**Comment by ecaruajulca2022** [comment]
A mi tambien me funciono

**Comment by hidetatz** [comment]
This issue is now fixed. Please reopen if it still happens.
