### ISSUE TITLE
kubectl debug prompt issue with kubecolor

### ISSUE THREAD

**Issue by ramanagali** [hidetatz/kubecolor#94]
Hello all,

I am trying to test Ephemeral Container using kube version v1.23.5  

after entering `kubectl debug -it ephemeral-demo --image=busybox:1.35 --target=ephemeral-demo`
i can see 2 issues..

1.  prompt displayed improper format. each line is different tab spaces etc
2. can’t see whatever i type at command prompt. After pressing enter.. i will be able to see along with result

**Issue:** 
![2022-03-31 14 40 26](https://user-images.githubusercontent.com/55323295/161364667-9fbf5143-fcc8-4479-bb40-9e60d7bde816.jpeg)

**When i remove `alias kubectl=kubecolor` it works as expected**
![2022-04-02 11 41 00](https://user-images.githubusercontent.com/55323295/161364808-62b6c219-8ed2-49c5-bc32-9d9b8d53b3f6.png)

Any workaround to fix this issue without removing?

**Comment by hidetatz** [comment]
I fixed the issue. just simply excluded 'debug' from colorization. Closing now.
