### ISSUE TITLE
Do not colorise output of kubecolor.exe __complete

### ISSUE THREAD

**Issue by nebula-it** [hidetatz/kubecolor#96]
Can we please add logic to always pass through the output of `kubecolor.exe __complete` in plain text. Without this in plain text it breaks the auto-completion in Powershell since Powershell calls this function to receive next arguments for auto-completion. Since users are not calling this directly it should not impact general workflow of kubecolor.

As a temporary workaround, I had this added in my Powershell autocomplete script
```
  if(((Get-Alias kubectl).Definition) -eq 'kubecolor'){
    $Program = $Program + ' --plain'
  }
```

I'm new at golang but happy to take a stab with some hand holding :)

**Comment by nebula-it** [comment]
Looks like this is fixed in https://github.com/hidetatz/kubecolor/pull/93

@hidetatz Can we please merge this?

**Comment by grzesuav** [comment]
I think I hit the issue with zsh...

**Comment by prune998** [comment]
This is fixed in the new clone of the project.
Get it at https://github.com/kubecolor/kubecolor 
or 
`brew install kubecolor/tap/kubecolor`
or 
`go install github.com/kubecolor/kubecolor/cmd/kubecolor@latest`

**Comment by hidetatz** [comment]
This should be fixed now. Please reopen if it still persists
